// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rrdvivxdasezvhfbetra.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJyZHZpdnhkYXNlenZoZmJldHJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwMzA5MzAsImV4cCI6MjA2NzYwNjkzMH0.7CSbIJa2G2b_RMOFh4AuDCE9dj3aXcEd_d7SBGWw-GU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});